apiVersion: v1
kind: Pod
metadata:
  name: vault-radar-csv-parser
  labels:
    app: vault-radar-csv-parser
spec:
  restartPolicy: Always
  containers:
  - name: vault-radar-csv-parser
    image: fwarfvinge/vault-radar-csv:latest
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vault-radar-csv-parser
spec:
  selector:
    app: vault-radar-csv-parser
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP  # Change to NodePort or LoadBalancer if you want external access
